# Generated by Django 5.1.1 on 2024-11-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=255, unique=True)),
                ('tasks', models.ManyToManyField(blank=True, to='Task.task')),
            ],
        ),
    ]
