# Generated by Django 5.1.1 on 2024-11-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tasks',
        ),
    ]
