# Generated by Django 5.1.1 on 2024-11-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Is_completed', models.BooleanField(default=False, verbose_name='Is task completed?')),
                ('Assign_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
